### ISSUE TITLE
CCTV上的视频可以下载，但是不能正常播放

### ISSUE THREAD

**Issue by def-fun** [Momo707577045/media-source-extract#10]
example：
https://tv.cctv.com/2021/04/15/VIDEmLG79SLltiYiLTl1E8Qj210415.shtml

**Comment by vmuu** [comment]
cctv的直接用Xtreme Download Manager下载
https://www.123pan.com/s/VZiA-7caVh

**Comment by vmuu** [comment]
自己去试了一下，可以正常下载播放的，下载下来的音频文件没有播放时间，不用理会，用ffmpeg直接与视频文件合并即可
