### ISSUE TITLE
视频禁止在小窗口播放，请关闭当前标签重新打开页面或重启浏览器继续播放！ #016

### ISSUE THREAD

**Issue by lbtlbbs** [Momo707577045/media-source-extract#12]
视频禁止在小窗口播放，请关闭当前标签重新打开页面或重启浏览器继续播放！ #016
插件不能用了吗？视频几秒后就会弹出上面的提示，何解？

**Comment by Momo707577045** [comment]
求链接，作者复现一下，查看原因

**Comment by william4s** [comment]
同样遇到了这个问题

**Comment by varSmallRookie** [comment]
大佬们，有解决办法吗

**Comment by vmuu** [comment]
遇到同样的问题

**Comment by varSmallRookie** [comment]
我最后改了网站的脚本，禁用了那段监听代码，再用charles拦截替换，目前只能这样解决

**Comment by vmuu** [comment]
> 我改了网站的脚本，禁止最后那这样解决代码，再用charles拦截段替换，目前只能

这个具体是怎么弄啊

**Comment by vmuu** [comment]
> 我改了网站脚本，杜绝最后那样解决，再用charles拦截代码替换，目前只能

禁止播放的那一段js是在哪里，找半天没找到

**Comment by Momo707577045** [comment]
问题已解决，访问以下链接以更新油猴插件
https://blog.luckly-mjw.cn/tool-show/media-source-extract/media-source-extract.user.js
最近才下定决心解决，拖更太久，实在抱歉。
感谢各位的反馈，有问题欢迎反馈

**Comment by varSmallRookie** [comment]
大佬 牛逼

毛静文 ***@***.***>于2022年10月10日 周一15:47写道：
