### ISSUE TITLE
下载了一集之后，没有清空之前的缓存，导致下载了之前的下载了好几遍

### ISSUE THREAD

**Issue by BeLinKang** [Momo707577045/media-source-extract#13]
有没有解决方案？

**Comment by BeLinKang** [comment]
我自己下载完之后重置一下那个列表解决了，
`// 下载资源
    function _download() {

      var _hmt = _hmt || [];
      (function() {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?1f12b0865d866ae1b93514870d93ce89";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
      })();
      _sourceBufferList.forEach((target) => {
        const mime = target.mime.split(';')[0]
        const type = mime.split('/')[1]
        const fileBlob = new Blob(target.bufferList, { type: mime }) // 创建一个Blob对象，并设置文件的 MIME 类型
        const a = document.createElement('a')
        a.download = `${document.title}.${type}`
        a.href = URL.createObjectURL(fileBlob)
        a.style.display = 'none'
        document.body.appendChild(a)
        a.click()
        a.remove()
      })
        _sourceBufferList = []  //这里新增的
    }`

**Comment by Momo707577045** [comment]
棒棒，动手能力强

**Comment by Momo707577045** [comment]
已采纳，哈哈，感谢
