### ISSUE TITLE
视频无画面但在线网页可以观看到

### ISSUE THREAD

**Issue by Super-Zoe** [Momo707577045/media-source-extract#14]
https://www.ixigua.com/6980995908372529700?logTag=b8e1a02f26400a723af6
你好，这个视频和音频下载成功了，唯独视频看不到什么东西，ffpmeg本地合成也没看见画面，但是上传到作者的在线网页观看却可以看到东西，不知道是什么原因~

**Comment by Momo707577045** [comment]
专属播放器现在提供离线版本咯，离线情况下也可以播放啦~
http://upyun.luckly-mjw.cn/lib/player-offline.html
