### ISSUE TITLE
建议输出为原格式

### ISSUE THREAD

**Issue by shap2zj** [Momo707577045/media-source-extract#15]
大佬

有些网站会用到多个m3u8同时播放。例如纯视频用一个m3u8，纯音频用另一个m3u8，然后两个同时播放。
这个插件在缓存合并的时候，会自动把ts文件合并成mp4，这样音频就会出一些问题（不知道是格式转换的问题还是我电脑的问题...）
建议直接输出为原格式ts，不自动转换为mp4说不定能解决音频乱码 :) 😁

**Comment by Momo707577045** [comment]
感谢反馈，用心了。
视频的格式是由浏览器决定的，传输用 ts，在进行解码，转化为 mp4 播放。而我们实在播放处进行数据拦截，所以必须是 mp4 的
