### ISSUE TITLE
我只是利用它倍速播放，但怎么恢复正常速度？

### ISSUE THREAD

**Issue by sun520999** [Momo707577045/media-source-extract#19]
我只是利用它倍速播放，但怎么恢复正常速度？
导致打开了同网站的视频，都是倍速。

**Comment by Momo707577045** [comment]
很抱歉遗留了这个问题，但作者这边暂时没有复现到，能提供一个视频链接吗？作者测试看看问题出在哪里

**Comment by Momo707577045** [comment]
已添加恢复倍数功能，点击十倍速后，再次点击会恢复一倍数播放，可通过最新的油猴插件实现最新效果
https://github.com/Momo707577045/media-source-extract/raw/master/media-source-extract.user.js
感谢反馈
