### ISSUE TITLE
视频下载后没声音

### ISSUE THREAD

**Issue by henryborner** [Momo707577045/media-source-extract#21]
我获取了一个视频，下载后没有声音，网址是https://www.iqiyi.com/v_19rrk0cguc.html?vfrm=pcw_playpage&vfrmblk=D&vfrmrst=80521_listbox_positive

**Comment by LuckyHookin** [comment]
我用来下载某疼视频时是有两个文件的：

1. 纯视频
2. 纯音频

所以要用小丸工具箱合并。

**Comment by Momo707577045** [comment]
正确情况下是会下载两个文件的，一个视频，一个音频
留意浏览器左上角的授权弹窗，允许多文件下载
