### ISSUE TITLE
请问下载时添加的百度脚本是干什么的

### ISSUE THREAD

**Issue by wtjperi2003** [Momo707577045/media-source-extract#24]
就是：https://hm.baidu.com/hm.js?1f12b0865d866ae1b93514870d93ce89，这个目前也打不开了
![微信截图_20211207112942](https://user-images.githubusercontent.com/10322892/144961093-38ed962b-2b27-4fa1-8768-708601ada519.png)

**Comment by Momo707577045** [comment]
这是百度统计用的，记录本工具的使用次数，但不会记录用户信息哈，可以放心使用
