### ISSUE TITLE
非常棒的脚本！我自己稍微改动了一下，可以不自动下载，而是让使用者自行选择是否下载。本人菜菜鸟，如有不当请海涵

### ISSUE THREAD

**Issue by zzgreg** [Momo707577045/media-source-extract#25]
//稍微改动了一下以下的地方

    // 监听资源全部录取成功
    let _endOfStream = window.MediaSource.prototype.endOfStream
    window.MediaSource.prototype.endOfStream = function() {
      if (!isClose) {
        //alert('资源全部捕获成功，即将下载！')
          let isDownLoadNow = confirm("资源全部捕获成功，共"+_sourceBufferList.length+"个。现在下载吗？")
          if(isDownLoadNow){
              _download()
              _endOfStream.call(this)
          }
      }
    }

**Comment by Momo707577045** [comment]
很棒的二次开发！要对自己有信心哦，能勇敢地发布 issues，进行技术交流，发表自己的想法，已经很棒了
