### ISSUE TITLE
大佬，为何这两处无效？

### ISSUE THREAD

**Issue by mashimaroinfo** [Momo707577045/media-source-extract#27]
大佬这个通吃插件牛了。试了几个网站，可以，但也有例外：

https://www.zhibo8.cc/other/2022/0123-b314280-svideo.htm

https://weibo.com/2995631244/Lc75RuT9T?layerid=4728872077361873

大佬过目看怎么回事

**Comment by Momo707577045** [comment]
哈哈，这种视频更容易提取，这种是使用 mp4 的视频格式，直接访问它的资源链接就可以直接下载。https://vodzz.duoduocdn.com/4a8d9c67vodtransgzp1251542705/85b38532387702295007706167/v.f100820.mp4
mp4 格式是将整个视频作为一个整体，对大视频的传输和播放不太友好，所以现代网站比较少使用这个格式了
如果有这方面需求，可以添加这个插件，也可以提取到
![image](https://user-images.githubusercontent.com/12947294/153543779-a1f48bbe-3794-4d1e-a617-e2d70b59f0f5.png)

**Comment by mashimaroinfo** [comment]
感谢解惑!
