### ISSUE TITLE
播放完自动退出

### ISSUE THREAD

**Issue by Marvll** [Momo707577045/media-source-extract#28]
倍速播放完毕，抓捕所有分段后还没下载就退出了（返回到播放列表）

**Comment by zealotCE** [comment]
> 倍速播放完毕，抓捕所有分段后还没下载就退出了（返回到播放列表）

建议你说一下情况，最好是链接给出来什么的吧？
不然，这个描述太模糊也没有办法定位的。

**Comment by le0zh0u** [comment]
这个应该是开启了播放完成自动返回。看是否在网站上进行设置，取消此项。而且这个页面动作，插件本身不好控制

**Comment by Momo707577045** [comment]
感谢两位的回复，确实如两位所说，需要在视频网站端进行配置解决
