### ISSUE TITLE
視頻自動下載建議去掉

### ISSUE THREAD

**Issue by velade** [Momo707577045/media-source-extract#33]
這個插件正常使用時會自動捕獲視頻，當全部片段捕獲完畢時會強制下載，不能取消，但是很多時候這是不需要的，尤其是有時會捕獲廣告，然後被迫下載一堆非目標的視頻。

建議，可以將啟用時機設為 右鍵選單啟用，這樣可以按需啟用這個插件（在代碼中標記 // @run-at       context-menu）不然用戶安裝時多數都不懂去油猴調整選項，發布的腳本那個設定頁面的是不會帶進去的。

或是把自動下載那裡的alert改為confirm，給用戶提供一個取消的選項。

我現在使用的是我自行修改過得，把_download()給註釋掉了

**Comment by zealotCE** [comment]
我觉得不一定要取消掉，或者可以你前端放一个开关，允许开启或者关闭即可。对我找的没有广告的资源其实这个自动下载挺省心的。

**Comment by velade** [comment]
> 我觉得不一定要取消掉，或者可以你前端放一个开关，允许开启或者关闭即可。对我找的没有广告的资源其实这个自动下载挺省心的。

其實關鍵問題是他的這個強制下載，其可能同一個網站，也不說有沒有廣告，但通常是有的視頻我想下載，有的不一定我就是要下載，因此一定是應該給用戶選擇的權力的。而且這個功能也要點一下確定，那我想下載的話，我點旁邊的浮窗也是可以的啊，那個上面也有下載按鈕，同樣都需要點一下滑鼠才能開始下載，那我認為這個功能即使去掉也不是什麼問題。

**Comment by velade** [comment]
其實這個腳本更好的一個處理方式是，直接依據視頻控件注入按鈕（可以浮在視頻上方角落），就像眾多的YouTube視頻下載腳本是直接在視頻下方的功能按鈕中加入了下載按鈕，就跟原本就有的功能一樣融合進去了，這樣有幾個好處，一是不強制下載了，可以根據需要去點一下才下載。第二是可以指定視頻，因為像是看推特 FB 之類的帖子，有一些有視頻，一頁可能很多個視頻，自動下載到底下的是哪一個？還是一口氣可能十幾個視頻都下載了？這就不太好了。

**Comment by zealotCE** [comment]
> 其實這個腳本更好的一個處理方式是，直接依據視頻控件注入按鈕（可以浮在視頻上方角落），就像眾多的YouTube視頻下載腳本是直接在視頻下方的功能按鈕中加入了下載按鈕，就跟原本就有的功能一樣融合進去了，這樣有幾個好處，一是不強制下載了，可以根據需要去點一下才下載。第二是可以指定視頻，因為像是看推特 FB 之類的帖子，有一些有視頻，一頁可能很多個視頻，自動下載到底下的是哪一個？還是一口氣可能十幾個視頻都下載了？這就不太好了。

针对你的那个场景，看起来确实是不太行。
不过我建议你可以考虑把自动播放关闭掉。
针对，现在这个功能，我建议你要么像现在这样注释掉下载，要么增加一个 switch 开关，这样就可以按需开启了。反正代码都看得见，改改嘛～

对我来说合适的原因是我现在用的网站都是单个视频的，不会自动播放，也没有广告，所以就没什么问题。
我都是点开网页，打开十倍速就够了。视频加载完了之后视频自动就下载下来了。接下来就是用脚本把音视频合并一下就可以了。

**Comment by Momo707577045** [comment]
pr 已合并，非常感谢各位的建设性意见
