### ISSUE TITLE
下載長影片chrome會報out of memory

### ISSUE THREAD

**Issue by Rinya416** [Momo707577045/media-source-extract#37]
如題
大約影片快到一個小時幾十分鐘
會報out of memory

配置
8700K+64g ram+3080

**Comment by Momo707577045** [comment]
是的，应该是视频体积太大，超过机器的内存了。
这种情况，只能通过分段抓取解决了。先提取前半部分视频，强制下载
再二次打开页面，跳到上次视频的结尾处。再将剩余的视频进行提取
