### ISSUE TITLE
每次刷新了页面后会有默认的9个片段在一开始就存在，我并没有播放视频？

### ISSUE THREAD

**Issue by MichaelPanwenjie** [Momo707577045/media-source-extract#38]
每次刷新了页面后会有默认的9个片段在一开始就存在,然而我并没有播放视频
并且在下载完后，也会重新提示有7或9个片段被检测到，
想请问一下，这个7到9个片段是如何产生的？

**Comment by Momo707577045** [comment]
网站进行了视频预缓存导致的片段被提前检查到？
具体原因得留一下网站地址，看代码确定了
