### ISSUE TITLE
它能有效避免到检测吗？

### ISSUE THREAD

**Issue by MichaelPanwenjie** [Momo707577045/media-source-extract#50]
发现有些网站对油猴有检测，然后就不能用了。
能有一段代码绕过检测吗？

**Comment by Momo707577045** [comment]
方便留一下网站地址吗？得调试过才知道

**Comment by MichaelPanwenjie** [comment]
https://www.easthome.com/

这个下面的所有的课播放时都会检测有没有用插件！

怎样能绕过检测呢？

**Comment by Momo707577045** [comment]
问题已解决，访问以下链接以更新油猴插件
https://blog.luckly-mjw.cn/tool-show/media-source-extract/media-source-extract.user.js

**Comment by MichaelPanwenjie** [comment]
更新了插件后，视频播放没有任何界面显示了，也没有提示下载了

**Comment by MichaelPanwenjie** [comment]
更新了 https://blog.luckly-mjw.cn/tool-show/media-source-extract/media-source-extract.user.js 后
现在播放视频没有任何插件界面提示下载了，请问这个最新插件是如何使用的？
