### ISSUE TITLE
遇到两个问题

### ISSUE THREAD

**Issue by LHS1998** [Momo707577045/media-source-extract#51]
使用平台: Chrome 105.0.5195.125, 油猴 v4.16.1, 脚本版本 0.6. 遇到以下两个问题:

1. 昨晚开始, 小鹅通的视频在捕捉完或点击下载已捕获片段后会弹出一个 blob: 开头的网页, 似乎是一个渲染失败的视频, 无法下载, 如图所示:
![截屏](https://user-images.githubusercontent.com/26176466/193379106-404fc798-55dc-400c-b384-cbc8531564fb.jpg)

2. 在网站 `https://www.luffycity.com/` 启用脚本时会提示 “视频禁止在小窗口播放”.
![截屏2](https://user-images.githubusercontent.com/26176466/193379185-a0e76213-ff47-4702-a8e2-034f002dbc55.png)

**Comment by Momo707577045** [comment]
第二个问题已解决，访问以下链接以更新油猴插件
https://blog.luckly-mjw.cn/tool-show/media-source-extract/media-source-extract.user.js

**Comment by Momo707577045** [comment]
第一个问题请附上测试链接，以便测试解决问题
