### ISSUE TITLE
捕获完毕无法下载

### ISSUE THREAD

**Issue by mumuxi-git** [Momo707577045/media-source-extract#52]
现在小鹅通似乎进行了进一步的加密，之前还可以下载，但现在下载会转到一个bob开头的网址（比如blob:https://app6wf7nmsr4708.h5.xiaoeknow.com/），也不会进行下载。

**Comment by Momo707577045** [comment]
方便留一下遇到问题的链接吗？以便测试复现问题

**Comment by williamzzcn123** [comment]
完全一样的问题，现在会自动转向一个blob开头的地址
blob:https://appc7ussfoc1579.h5.xiaoeknow.com/4529606c-7965-40a6-9dcc-91386987678c

**Comment by MrJohnRobert** [comment]
> 方便留一下遇到问题的链接吗？以便测试复现问题

登录之后有试看课程，捕获之后就会自动转向一个blob开头的地址，这是视频链接https://cvlife.net/detail/term_61a6d81936cf2_N64ZPM/25?product_id=term_61a6d81936cf2_N64ZPM

**Comment by strivecheng** [comment]
我也遇到了

**Comment by strivecheng** [comment]
> 下载成功了，做了以下几步：
> 
> 1. 在 Tampermonkey 的 setting 里，选择 advanced，在 Security 里的 Modify existing content security policy (CSP) headers 改成 Remove entirely (possibly unsecure)。不这么做 stream-saver.js 会被 block 掉。
> 2. 在代码的 _download() function 里，添加 `a.setAttribute("target", "_blank")` 让blob在同一页打开，不然无法读取 blob 内容。
> 3. 我用的是 Chrome，首次下载地址栏右边会显示 pop-up block，同意 pop-up 就可以了。

谢谢你提供的方案。我这边设置后确实可以下载了，但是视频没有画面，声音也是想 10 倍慢放变声一样，麻烦这该怎么解决呢？谢谢。 @mybluedog24

**Comment by strivecheng** [comment]
> 下载成功了，做了以下几步：
> 
> 1. 在 Tampermonkey 的 setting 里，选择 advanced，在 Security 里的 Modify existing content security policy (CSP) headers 改成 Remove entirely (possibly unsecure)。不这么做 stream-saver.js 会被 block 掉。
> 2. 在代码的 _download() function 里，添加 `a.setAttribute("target", "_blank")` 让blob在同一页打开，不然无法读取 blob 内容。
> 3. 我用的是 Chrome，首次下载地址栏右边会显示 pop-up block，同意 pop-up 就可以了。

        a.setAttribute("target", "_blank")这行代码在_download里面加的位置有要求吗？

**Comment by Momo707577045** [comment]
这是因为小鹅通对点击事件进行了拦截
问题已解决，本地测试通过，点击以下链接完成插件更新，重试即可
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js

**Comment by mumuxi-git** [comment]
非常感谢，测试已经可以下载了，[image: image.png]

毛静文 ***@***.***> 于2022年10月23日周日 19:59写道：

**Comment by mybluedog24** [comment]
> > 下载成功了，做了以下几步：
> > 
> > 1. 在 Tampermonkey 的 setting 里，选择 advanced，在 Security 里的 Modify existing content security policy (CSP) headers 改成 Remove entirely (possibly unsecure)。不这么做 stream-saver.js 会被 block 掉。
> > 2. 在代码的 _download() function 里，添加 `a.setAttribute("target", "_blank")` 让blob在同一页打开，不然无法读取 blob 内容。
> > 3. 我用的是 Chrome，首次下载地址栏右边会显示 pop-up block，同意 pop-up 就可以了。
> 
> 谢谢你提供的方案。我这边设置后确实可以下载了，但是视频没有画面，声音也是想 10 倍慢放变声一样，麻烦这该怎么解决呢？谢谢。 @mybluedog24

应该是解码问题，估计需要转码，可以试试 ffmpeg。
