### ISSUE TITLE
这个网站下载完了无法打开

### ISSUE THREAD

**Issue by JXA-a** [Momo707577045/media-source-extract#53]
老大 这个网站下载完了 视频无法打开 我可以提供一个测试的链接 你可以试试吗？

https://watch.indee.tv/indee/

因为链接有打开次数 所以如果可以的话  我单独发你的邮箱 希望得到你的回复

**Comment by Momo707577045** [comment]
该链接已无法打开，若再次复现，可联系我 QQ：707577045

**Comment by JXA-a** [comment]
已经加你了 请通过
