### ISSUE TITLE
这个m3u8文件内把ts重命名为png的后缀了，可以识别到，但是下载后无法合并

### ISSUE THREAD

**Issue by apollyonx** [Momo707577045/media-source-extract#54]
如题：
问题链接：https://file.service.qq.com/outside-files/20221016/202210162212434095.png
识别后跳转到：http://laohu666.bj01.bdysite.com/admin/?key=JjULKz84KBYMLSYSJTw8FSs7JjcmNSYRFCQzXws2ORs+OyAVMwY9DD4MFwAXXgleJh81UyMFPx0sKy0ANQw9XRZeDV8yJlkLDVpFACwEMh02Jl4YFwU0FjoZIi86BExeADg6GQ4YOhEnAA04OkQ1GSECLF0uOyFAIiUEEDkBURUMIQsNIgI8ACwEJRkhCyUDEV8OAyUfJQ0iWDAALAUiGggpPR8WFTQVOSY5GD0BIBUzASYDCDklGzkBLxoiISYmIC8RIzAEGCYmNSYRPzgFKg==

从页面中获取到m3u8链接为：http://laohu666.bj01.bdysite.com/admin/SMR_video/YVGV1665929491.m3u8

可直接下载m3u8文件；
但无法合并，或者合并后时长正确，但无画面；

**Comment by Momo707577045** [comment]
本地测试没有问题哦，成功下载一个视频文件，一个音频文件。
使用专属播放器播放器正常
http://blog.luckly-mjw.cn/tool-show/media-source-extract/player/player.html
