### ISSUE TITLE
腾讯会议录屏无法下载

### ISSUE THREAD

**Issue by liuhanqing-phy** [Momo707577045/media-source-extract#55]
按照步骤打开源代码发现是空白
https://meeting.tencent.com/user-center/shared-record-info?id=e6b1f9ea-ec08-48ba-8fdb-8b703366c1d6

**Comment by Momo707577045** [comment]
初步看，是因为腾讯会议使用的是完全不同的技术，没有使用到响应的 API，
是个好问题，我有空看看

**Comment by Momo707577045** [comment]
腾讯会议的视频协议比较原始，用的是 mp4，还不需要用到无差别。我将功能集成到 m3u8 下载工具里面了，访问这个链接更新试试
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
有效果回复一下哈
