### ISSUE TITLE
直播流DOUYU的视频录制问题/声音变粗失真

### ISSUE THREAD

**Issue by jggnice** [Momo707577045/media-source-extract#62]
DOUYU的视频录制问题:
声音变粗失真
专属播放器也不能播放
(PS: 有些网站的录制会声音变粗失真或声画不同步可以用专属播放器解决)

**Comment by jggnice** [comment]
已解决: 
使用 **VLC Media Player**

**Comment by Jebroll** [comment]
感谢，我也遇到这个问题了，使用 VLC Media Player

**Comment by Jebroll** [comment]
感谢，我也遇到这个问题了，用 VLC Media Player 解决了
