### ISSUE TITLE
视频时差限制为4分钟

### ISSUE THREAD

**Issue by SQXhombre** [Momo707577045/media-source-extract#8]
你好，插件惊为天人
最近遇到一个问题，现在的视频时差极限在4分钟，超出4分钟的部分，无法下载，怎么解决呢

**Comment by Momo707577045** [comment]
你好，方便的话，附一下视频地址，需要调试才知道问题所在

**Comment by SQXhombre** [comment]
谢谢作者的回复，我的视频是加密视频，是属于付费才能看到的内容，付费内容会过期，所以才想着下载下来，发链接的话，怕是引起别人的注意，我用录屏的方法解决，再次感谢！

**Comment by Momo707577045** [comment]
好的，感谢回复。
