### ISSUE TITLE
西瓜视频无法提取

### ISSUE THREAD

**Issue by ltovem** [Momo707577045/media-source-extract#81]
打开插件以后，西瓜视频有版权的电影电视 提示无法播放

**Comment by Momo707577045** [comment]
留一下视频地址，我本地测试看看

**Comment by ltovem** [comment]
[电视剧比如亮剑](https://www.ixigua.com/6699356792905794055?id=6699406556213019150&logTag=d352a76fa7a652879581)，应该是被检测到hook了

**Comment by Momo707577045** [comment]
好的，我抽空看看

**Comment by Momo707577045** [comment]
检测突破已实现，再次感谢反馈

**Comment by Momo707577045** [comment]
点击以下链接，完成插件更新：
https://blog.luckly-mjw.cn/tool-show/media-source-extract/media-source-extract.user.js
