### ISSUE TITLE
西瓜视频下载后只有五秒

### ISSUE THREAD

**Issue by ltovem** [Momo707577045/media-source-extract#82]
例如两件[西瓜视频亮剑](xigua.com/6699356792905794055?id=6699406556213019150&logTag=d352a76fa7a652879581)
下载完不管视频文件多大只能看五秒整片之前的，整片开始以后就无法播放

**Comment by ltovem** [comment]
有遇到类似问题的同学吗？

**Comment by FlyDut** [comment]
问题描述应该跟我刚才遭遇的一样，可能是缺少元数据导致解码失败。解决方法我写在另一问题下了
https://github.com/Momo707577045/media-source-extract/issues/84

**Comment by Momo707577045** [comment]
官网好像修复了这个问题咯，现在使用插件可以正常下载，正常播放
