### ISSUE TITLE
这个网站上的视频检测不到啊

### ISSUE THREAD

**Issue by royalzeng** [Momo707577045/media-source-extract#86]
https://www.kankanews.com/detail/AZQYL3z7myd

**Comment by rictt** [comment]
这个是MP4直接播放的，不经过MSE，视频右键可以下载

**Comment by Momo707577045** [comment]
现在 MP4 也支持下载了，我将功能集成到 m3u8 下载工具里面了，访问这个链接更新试试
https://blog.luckly-mjw.cn/tool-show/m3u8-downloader/m3u8-downloader.user.js
